### ISSUE TITLE
Prepare for the public disclosure

### ISSUE THREAD

**Issue by hanjukim** [terra-money/terra-wallet-java#1]
This repo will enable developers to add features that requires create, load and sign transactions to  their apps.

@ouiliame and @path0509 will review and update this repo to be made public from next week.

**Comment by path0509** [comment]
Libraries were included terra-wallet-android
- MIT License / https://github.com/MasterEx/java-base64/blob/master/src/pntanasis/base64/base64.java
- MIT License / https://github.com/WebOfTrustInfo/txref-conversion-java/blob/master/src/main/java/info/weboftrust/txrefconversion/Bech32.java
- MIT License / https://github.com/nayuki/Bitcoin-Cryptography-Library/blob/master/java/io/nayuki/bitcoin/crypto/Ripemd160.java
- MIT License / https://github.com/meyfa/java-sha256
- Apache License 2.0 / https://github.com/web3j/web3j
- Apache License 2.0 / https://github.com/google/gson
- Other License (https://github.com/stleary/JSON-java/blob/master/LICENSE) / https://github.com/stleary/JSON-java

**Comment by path0509** [comment]
Todo:
make "bip" optional
~~~java
TerraWalletSDK.getNewWalletFromSeed(mnemonic, bip(optional))
~~~

done.(20200414, branch: make-testcase)
~~~java
TerraWalletSDK.getNewWalletFromSeed(mnemonic) // *added method, default bip set 330
TerraWalletSDK.getNewWalletFromSeed(mnemonic, bip)
~~~
