### ISSUE TITLE
transferTest error

### ISSUE THREAD

**Issue by AriesChain-Dev** [terra-money/terra-wallet-java#3]
hello sir:
 I encountered such an error during the transfer process

response : {"codespace":"sdk","code":4,"gas_used":"42970","gas_wanted":"200000","raw_log":"signature verification failed; please verify account number (4429731), sequence (71) and chain-id (columbus-5): unauthorized","logs":null,"events":null,"txhash":"BC814ED7A181F6175A06C499D14F1F2582F1037A5AF9C7883DDCB4767EF4C3BF"}

**Comment by hanny15** [comment]
Have you solved your problem?
